name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.5'
        cache: true

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build for Linux AMD64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -X "github.com/jaepetto/nbjrnlctl/internal/version.Version=1.0.0" -X "github.com/jaepetto/nbjrnlctl/internal/version.GitCommit=$(git rev-parse HEAD)" -X "github.com/jaepetto/nbjrnlctl/internal/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"' -o bin/nbjrnlctl-linux-amd64 ./cmd/nbjrnlctl

    - name: Build for Linux ARM64
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -ldflags '-extldflags "-static" -X "github.com/jaepetto/nbjrnlctl/internal/version.Version=1.0.0" -X "github.com/jaepetto/nbjrnlctl/internal/version.GitCommit=$(git rev-parse HEAD)" -X "github.com/jaepetto/nbjrnlctl/internal/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"' -o bin/nbjrnlctl-linux-arm64 ./cmd/nbjrnlctl

    - name: Build for Darwin AMD64
      run: |
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -X "github.com/jaepetto/nbjrnlctl/internal/version.Version=1.0.0" -X "github.com/jaepetto/nbjrnlctl/internal/version.GitCommit=$(git rev-parse HEAD)" -X "github.com/jaepetto/nbjrnlctl/internal/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"' -o bin/nbjrnlctl-darwin-amd64 ./cmd/nbjrnlctl

    - name: Build for Darwin ARM64
      run: |
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -a -ldflags '-extldflags "-static" -X "github.com/jaepetto/nbjrnlctl/internal/version.Version=1.0.0" -X "github.com/jaepetto/nbjrnlctl/internal/version.GitCommit=$(git rev-parse HEAD)" -X "github.com/jaepetto/nbjrnlctl/internal/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"' -o bin/nbjrnlctl-darwin-arm64 ./cmd/nbjrnlctl

    - name: Build for Windows AMD64
      run: |
        CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -X "github.com/jaepetto/nbjrnlctl/internal/version.Version=1.0.0" -X "github.com/jaepetto/nbjrnlctl/internal/version.GitCommit=$(git rev-parse HEAD)" -X "github.com/jaepetto/nbjrnlctl/internal/version.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)"' -o bin/nbjrnlctl-windows-amd64.exe ./cmd/nbjrnlctl

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nbjrnlctl-binaries
        path: bin/
        if-no-files-found: error
